### PR TITLE
K8S patch and other clean up items

### PR DESCRIPTION
**Pull request by jimhopkinsjr**
## Description
Updates to rak8s for a new installation on freshly installed b+'s 
Commit notes are pretty lengthy, but here is the synopsis:
1. Updated base k8s version to something that isn't vulnerable.
2. Removed control path setting as it wasn't working on my ubuntu 16.04 vm /shrug
3. Updated some flannel logic
4. moved a few things around in how apt-get is handled.

## Testing
3 new raspberry pi b+'s
1. ran installation -> successful
2. ran cleanup 
3. ran installation again

## Issue Number
My change fixes issue #50

### CODE REVIEW

**Comment by StoicPerlman** [comment]
Just confirming this installs v1.13.1 without issue for me

**Comment by chris-short** [comment]
python-apt probably needs to be available prior to calling apt with python. Also, there are some conflicts.

**Comment by jimhopkinsjr** [comment]
@chris-short I'll get this cleaned up.  I saw the PR's and assumed it would have conflicts.  

Thanks

**Comment by sbaeurle** [comment]
hey @jimhopkinsjr what's the current status of your clean-up? do you need some help or are you mostly done?`

(I'm planning to use rak8s but want to wait till version 1.13.1)

**Comment by jimhopkinsjr** [comment]
@sbaeurle picking this up again now.  I'll updated when its there

**Comment by chris-short** [comment]
Thank you Jim.

**Comment by jimhopkinsjr** [comment]
@chris-short  - I'm not super happy with how the changes I've introduced are laid
out are so I'll likely submit another PR (not idempotent, PI restarts are
always firing).  Also a this point when adding a new node the GPU check
failed, so I need to fix that since it responded with an rc 1.

.edit. tagging right chris.... :fail:

**Pull request merged**
