### PR TITLE
Kubelet install failure and deprecation warning fix (#58)

### PR DESCRIPTION
**Pull request by chris-short**
* Squashed commit of the following:

commit 22cad03f2d0fe03da1abed89a3f11e5cf684b0b5
Author: Chris Short <chris@chrisshort.net>
Date:   Mon Jan 15 17:52:36 2018 -0500

    removing ignorable files

commit 89e1199ccbd24ba495789b79fcffcdae90010f57
Author: Chris Short <chris@chrisshort.net>
Date:   Mon Jan 15 17:47:06 2018 -0500

    Updating .gitignore

    Signed-off-by: Chris Short <chris@chrisshort.net>

commit e90c58b8e785aebc4432b53fe08935d3f16012ad
Author: Chris Short <chris@chrisshort.net>
Date:   Mon Jan 15 17:43:53 2018 -0500

    Initial rak8s Commit

Signed-off-by: Chris Short <chris@chrisshort.net>

* Set theme jekyll-theme-tactile

* Create CNAME

* link to how to change size of video memory

Closes #1.

* Update mechanism to enable cgroup memory

See: https://github.com/raspberrypi/linux/commit/ba742b52e5099b3ed964e78f227dc96460b5cdc0

* why not both?

I found the elimination of cgroup_enable=memory actually broke my raspbian kubernetes setup. putting both worked with my testing after reboot.

* k8s upgrade role init

Signed-off-by: Chris Short <chris@chrisshort.net>

* upgrade playbook ready

Signed-off-by: Chris Short <chris@chrisshort.net>

* Updating README

Adding link to Discourse site

Signed-off-by: Chris Short <chris@chrisshort.net>

* Adding Code of Conduct

Long overdue

Signed-off-by: Chris Short <chris@chrisshort.net>

* Create issue_template.md

* issue_template.md: release file path correction

/etc/os-release has the preferred data

Signed-off-by: Chris Short <chris@chrisshort.net>

* Changed deprecated URL https://git.io/weave-kube to https://cloud.weave.works/k8s/net?k8s-version=<version>

* Adding PR template

* Move TASK [Pass bridged IPv4 traffic to iptables' chains] after TASK [kubeadm : Run Docker Install Script]

* Changed networking from weave to flannel. Added version control for docker-ce, kubeadm, kubelet, kubectl, kubernetes images and flannel.

* Added cleanup playbook that removes kubernetes, all images, docker-ce, kubeadm, kubelet, kubectl and performs a reboot.

* Cleaning Up/Organizing/Adding Functionality

- Incorporate changes from #34
- Changing soon to be deprecated Ansible syntaxes
- Adding a backup option for /root/.kube/config
- Set hostname from inventory
- Adding version options to group_vars

Signed-off-by: Chris Short <chris@chrisshort.net>

* Backup Option

Signed-off-by: Chris Short <chris@chrisshort.net>

* Add troubleshooting steps and timing adjustments (#37)

* Troubleshooting Steps

updating README with some info that helped me when following the documentation

* Timeout Changes

Allows for slowed nodes to be recognized

* Timeout Changes

* v0.2.1

This version matching appears to be working as desired on three Raspberry Pi 3B+

The inventory file is breaking up my six node stack into two clusters. This will enable easier development.

A force flag has been added to kubeadm reset

Signed-off-by: Chris Short <chris@chrisshort.net>

* Fix 'Need to Start Over' script name (#40)

* Applying podnet variable correctly

Not sure how that even happened.

Signed-off-by: Chris Short <chris@chrisshort.net>

* Lock docker version to currently installed version when it is installed (#44)

* Ignore failing deletion of swap (#46)

- Due to using hypriot, which doesn't have dphys-swapfile installed by
default, the current deletion process fails.  Adding `ignore_errors`
fixes this.

TASK [kubeadm : Disable Swap] **************************************************************************************************************************************************************************************************************************************************
fatal: [rak8s000]: FAILED! => {"changed": true, "cmd": "dphys-swapfile swapoff && dphys-swapfile uninstall && update-rc.d dphys-swapfile remove", "delta": "0:00:00.005302", "end": "2018-12-24 20:35:44.430288", "msg": "non-zero return code", "rc": 127, "start": "2018-12-24 20:35:44.424986", "stderr": "/bin/sh: 1: dphys-swapfile: not found", "stderr_lines": ["/bin/sh: 1: dphys-swapfile: not found"], "stdout": "", "stdout_lines": []}
...ignoring

* reduce gpu memory (#48)

* update dashboard url (#47)

* K8S patch and other clean up items (#51)

* updated ansible configs to no longer use control paths as this failed on ubuntu 16.04 when deploying

* 50 - updated k8s version to latest release, updated docker, using flannel master currently as this is the only version that worked out of the box with k8s 1.13.1 - jh

* moved python apt dependency below apt-get update to allow for new installations to update cache prior installing, fixed reboot with logic from cleanup.yml

* removed apt-get update from kubeadm main since this is in common main and added environment var to stop apt from being angry - jh

* flannel at master now supports arm and amd64 k8s labels, as such we don't need to deal with this anymore.

* more updates for 1.14, removed gpu check since it's not longer working on my pi's and failing with a nonzero exit code.

* Altered apt syntax

Packages specified as an array in pkg rather than in with_items resolves "Invoking 'apt' only once while using a loop via squash_actions is deprecated" warning

* update_cache added

Resolves "No package matching 'kubelet' is available" error

## Issue Number
My change fixes issue #

### CODE REVIEW

**Comment by chris-short** [comment]
@PostlMC I don't think this is what you wanted.

**Comment by postlmc** [comment]
Ugh, yeah.  Something's not right here.  I'm not sure what I did that made my PR want to roll up all this.

**Comment by exotime** [comment]
For what it's worth, this branch worked for me when master did not.

**Comment by MatthiasLohr** [comment]
Anything new on this?

**Comment by chris-short** [comment]
See Issue #60 for resolution.

**Pull request closed without merging**
